# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    configuration: 'Debug'
    arguments: '-r linux-x64'
    zipAfterPublish: true

- task: CmdLine@2
  inputs:
    script: |
      echo "Agent.WorkFolder"
      echo "$(Agent.WorkFolder)"
      tree $(Agent.WorkFolder)\1 /f
      
      echo "Build.ArtifactStagingDirectory:" 
      echo "$(Build.ArtifactStagingDirectory)"
      tree $(Build.ArtifactStagingDirector)\1 /f
      
      echo "Build.BinariesDirectory:" 
      echo "$(Build.BinariesDirectory)"
      
      echo "Build.SourcesDirectory:"
      echo "$(Build.SourcesDirectory)"